// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"lifelog-grpc/comment/grpc"
	"lifelog-grpc/comment/ioc"
	"lifelog-grpc/comment/repository"
	"lifelog-grpc/comment/repository/dao"
	"lifelog-grpc/comment/service"
)

// Injectors from wire.go:

func InitCommentServiceGRPCService() *grpc.CommentServiceGRPCService {
	logger := ioc.InitLogger()
	db := ioc.GetMysql(logger)
	commentDao := dao.NewCommentDaoGorm(db, logger)
	commentRepository := repository.NewCommentRepository(commentDao)
	commentService := service.NewCommentService(commentRepository)
	kafkaProducer := ioc.InitKafka()
	commentServiceGRPCService := grpc.NewCommentServiceGRPCService(commentService, kafkaProducer, logger)
	return commentServiceGRPCService
}

// wire.go:

var commentSet = wire.NewSet(service.NewCommentService, repository.NewCommentRepository, dao.NewCommentDaoGorm)

var third = wire.NewSet(ioc.InitLogger, ioc.GetMysql, ioc.InitKafka)
