// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"lifelog-grpc/event/commentEvent"
	"lifelog-grpc/event/lifeLogEvent"
	repository2 "lifelog-grpc/interactive/repository"
	cache2 "lifelog-grpc/interactive/repository/cache"
	"lifelog-grpc/interactive/repository/dao"
	service2 "lifelog-grpc/interactive/service"
	"lifelog-grpc/ioc"
	"lifelog-grpc/ranking/repository"
	"lifelog-grpc/ranking/repository/cache"
	"lifelog-grpc/ranking/service"
	"lifelog-grpc/web"
)

// Injectors from wire.go:

func InitApp() *App {
	userServiceClient := ioc.InitUserServiceGRPCClient()
	logger := ioc.InitLogger()
	jwtHandler := web.NewJWTHandler(logger)
	userHandler := web.NewUserHandler(userServiceClient, logger, jwtHandler)
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(logger, cmdable)
	lifeLogServiceClient := ioc.InitLifeLogServiceCRPCClient()
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := lifeLogEvent.NewSaramaSyncProducer(syncProducer)
	interactiveServiceClient := ioc.InitInteractiveServiceGRPCClient(logger)
	lifeLogHandler := web.NewLifeLogHandler(logger, lifeLogServiceClient, producer, interactiveServiceClient)
	collectServiceClient := ioc.InitCollectServiceGRPCClient(logger)
	collectHandler := web.NewCollectHandler(collectServiceClient, logger)
	commentServiceClient := ioc.InitCommentServiceGRPCClient(logger)
	commentHandler := web.NewCommentHandler(logger, commentServiceClient)
	codeServiceClient := ioc.InitCodeServiceGRPCClient(logger)
	codeHandler := web.NewCodeHandler(logger, codeServiceClient)
	rankingCache := cache.NewRankingCacheRedis(cmdable)
	rankingRepository := repository.NewRankingRepository(rankingCache)
	rankingService := service.NewRankingService(rankingRepository)
	job := ioc.InitRankingJob(rankingService, logger, cmdable)
	interactiveHandler := web.NewInteractiveHandler(logger, interactiveServiceClient, job, producer)
	engine := ioc.InitGin(userHandler, v, lifeLogHandler, collectHandler, commentHandler, codeHandler, interactiveHandler)
	db := ioc.GetMysql(logger)
	interactiveDao := dao.NewInteractiveDao(db, logger)
	interactiveCache := cache2.NewInteractiveCache(cmdable, logger)
	interactiveRepository := repository2.NewInteractiveRepository(interactiveDao, interactiveCache)
	interactiveService := service2.NewInteractiveService(interactiveRepository)
	readEventConsumer := lifeLogEvent.NewReadEventConsumer(client, logger, interactiveService)
	v2 := ioc.InitConsumers(readEventConsumer)
	cron := ioc.InitCronRankingJob(logger, job)
	app := &App{
		server:    engine,
		consumers: v2,
		cron:      cron,
	}
	return app
}

// wire.go:

// userSet user模块的依赖注入
var userSet = wire.NewSet(web.NewUserHandler, ioc.InitUserServiceGRPCClient)

// codeSet code模块的依赖注入
var codeSet = wire.NewSet(web.NewCodeHandler, ioc.InitCodeServiceGRPCClient)

// JwtSet 初始化jwt模块
var JwtSet = wire.NewSet(web.NewJWTHandler)

// LifeLog模块
var lifeLogSet = wire.NewSet(web.NewLifeLogHandler, ioc.InitLifeLogServiceCRPCClient)

// collectClipSet collectClip模块的依赖注入
var collectClipSet = wire.NewSet(web.NewCollectHandler, ioc.InitCollectServiceGRPCClient)

// interactiveSet interactive模块的依赖注入
var interactiveSet = wire.NewSet(web.NewInteractiveHandler, ioc.InitInteractiveServiceGRPCClient)

// commentSet 评论
var commentSet = wire.NewSet(web.NewCommentHandler, ioc.InitCommentServiceGRPCClient)

// kafkaSet kafka模块的依赖注入
var kafkaSet = wire.NewSet(ioc.InitKafka, lifeLogEvent.NewReadEventBatchConsumer, lifeLogEvent.NewReadEventConsumer, lifeLogEvent.NewSaramaSyncProducer, commentEvent.NewCommentEventBatchConsumer, ioc.InitConsumers, ioc.InitSyncProducer, service2.NewInteractiveService, repository2.NewInteractiveRepository, dao.NewInteractiveDao, cache2.NewInteractiveCache)

// rankingSet ranking模块的依赖注入
var rankingSet = wire.NewSet(service.NewRankingService, repository.NewRankingRepository, cache.NewRankingCacheRedis)

// rankingJobCronSet 热榜定时任务的依赖注入
var rankingJobCronSet = wire.NewSet(ioc.InitRankingJob, ioc.InitCronRankingJob)
