// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"lifelog-grpc/file/grpc"
	"lifelog-grpc/file/ioc"
	"lifelog-grpc/file/repository"
	"lifelog-grpc/file/repository/dao"
	"lifelog-grpc/file/service"
)

// Injectors from wire.go:

func InitFileServiceGRPCService() *grpc.FileServiceGRPCService {
	logger := ioc.InitLogger()
	db := ioc.GetMysql(logger)
	fileDao := dao.NewFileService(db, logger)
	fileRepository := repository.NewFileService(fileDao)
	fileService := service.NewFileService(fileRepository, logger)
	fileServiceGRPCService := grpc.NewFileServiceGRPCService(fileService)
	return fileServiceGRPCService
}

// wire.go:

var fileSet = wire.NewSet(service.NewFileService, repository.NewFileService, dao.NewFileService)

var thirdSet = wire.NewSet(ioc.InitMinio, ioc.InitLogger, ioc.GetMysql)
