db:
    mysql:
        dsn: "root:123456@tcp(localhost:3306)/lifelog?charset=utf8mb4&parseTime=True&loc=Local"

redis:
    addr: "127.0.0.1:6379"
    password: ""
    db: 0

commentKafka:
    addr:
        - "localhost:9092"
    topic: "comments"

grpc:
    secure : false

userEtcd:
    port: 8070
    addr:
        - "localhost:12379"

codeEtcd:
    port: 8071
    addr:
        - "localhost:12379"

lifeLogEtcd:
    port: 8072
    addr:
        - "localhost:12379"

interactiveEtcd:
    port: 8073
    addr:
        - "localhost:12379"

collectEtcd:
    port: 8074
    addr:
        - "localhost:12379"

commentEtcd:
    port: 8075
    addr:
        - "localhost:12379"

commentConsumer:
    addr:
        - "localhost:9092"
    groupId: "commentGroup"
    topic:  "comments"
    timeout: 1
    batch: 10
