db:
    mysql:
        dsn: "root:123456@tcp(localhost:3306)/lifelog?charset=utf8mb4&parseTime=True&loc=Local"

redis:
    addr: "127.0.0.1:6379"
    password: ""
    db: 0

grpc:
    secure : false

userEtcd:
    port: 8070
    addr:
        - "localhost:12379"

codeEtcd:
    port: 8071
    addr:
        - "localhost:12379"

lifeLogEtcd:
    port: 8072
    addr:
        - "localhost:12379"

interactiveEtcd:
    port: 8073
    addr:
        - "localhost:12379"

collectEtcd:
    port: 8074
    addr:
        - "localhost:12379"

commentEtcd:
    port: 8075
    addr:
        - "localhost:12379"

fileEtcd:
    port: 8076
    addr:
        - "localhost:12379"

feedEtcd:
    port: 8077
    addr:
        - "localhost:12379"

commentKafka:
    addr:
        - "localhost:9092"
        - "localhost:9094"
    groupId: "commentGroup"
    topic: "comments"
    timeout: 1
    batch: 3

LikedKafka:
    addr:
        - "localhost:9092"
        - "localhost:9094"

minio:
    endpoint: "localhost:9000"
    accessKey: "RaEKllxArIYNXNu7WIay"
    secretKey: "9SkofrJa1DA3vwF1NHEgbzt86ozoLr4b8rEtCJzS"
    # 是否使用SSL，如果使用SSL，endpoint url必须以https开头
    # false不启用，true启用
    useSSL: false


