// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"lifelog-grpc/collect/grpc"
	"lifelog-grpc/collect/ioc"
	"lifelog-grpc/collect/repository"
	"lifelog-grpc/collect/repository/dao"
	"lifelog-grpc/collect/service"
)

// Injectors from wire.go:

// InitCollectServiceGRPCService 初始化CollectServiceGRPCService
func InitCollectServiceGRPCService() *grpc.CollectServiceGRPCService {
	logger := ioc.InitLogger()
	db := ioc.GetMysql(logger)
	collectDao := dao.NewCollectDao(db, logger)
	collectRepository := repository.NewCollectRepository(collectDao)
	collectService := service.NewCollectService(collectRepository)
	collectServiceGRPCService := grpc.NewCollectServiceGRPCService(collectService)
	return collectServiceGRPCService
}

// wire.go:

// collectSet 注入
var collectSet = wire.NewSet(repository.NewCollectRepository, dao.NewCollectDao, service.NewCollectService)

var third = wire.NewSet(ioc.InitLogger, ioc.GetMysql, ioc.InitLifeLogServiceCRPCClient)
