// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"lifelog-grpc/files/grpc"
	"lifelog-grpc/files/ioc"
	"lifelog-grpc/files/repository"
	"lifelog-grpc/files/repository/dao"
	"lifelog-grpc/files/service"
)

// Injectors from wire.go:

func InitFileServiceGRPCService() *grpc.FilesServiceGRPCService {
	logger := ioc.InitLogger()
	db := ioc.GetMysql(logger)
	fileDao := dao.NewFileDao(db, logger)
	fileRepository := repository.NewFileService(fileDao)
	fileService := service.NewFileService(fileRepository, logger)
	filesServiceGRPCService := grpc.NewFileServiceGRPCService(fileService)
	return filesServiceGRPCService
}

// wire.go:

var fileSet = wire.NewSet(service.NewFileService, repository.NewFileService, dao.NewFileDao)

var thirdSet = wire.NewSet(ioc.InitLogger, ioc.GetMysql)
