// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"lifelog-grpc/lifeLog/event"
	"lifelog-grpc/lifeLog/grpc"
	"lifelog-grpc/lifeLog/repository"
	"lifelog-grpc/lifeLog/repository/cache"
	"lifelog-grpc/lifeLog/repository/dao"
	"lifelog-grpc/lifeLog/service"
	"lifelog-grpc/lifelog/ioc"
)

// Injectors from wire.go:

func InitLifeLogServiceGRPCService() *App {
	logger := ioc.InitLogger()
	db := ioc.GetMysql(logger)
	lifeLogDao := dao.NewLifeLogDao(db, logger)
	cmdable := ioc.InitRedis()
	lifeLogCache := cache.NewLifeLogRedisCache(cmdable, logger)
	cacheCache := ioc.InitGoCache()
	localCache := cache.NewLocalCache(cacheCache)
	lifeLogRepository := repository.NewLifeLogRepository(lifeLogDao, logger, lifeLogCache, localCache)
	lifeLogService := service.NewLifeLogService(lifeLogRepository)
	lifeLogServiceGRPCService := grpc.NewLifeLogServiceGRPCService(lifeLogService, logger)
	client := ioc.InitSaramaKafka(logger)
	asyncLifeLogEventConsumer := event.NewAsyncLifeLogEventConsumer(client, logger, lifeLogService)
	app := &App{
		lifeLogServiceGRPCService: lifeLogServiceGRPCService,
		asyncLifeLogEventConsumer: asyncLifeLogEventConsumer,
	}
	return app
}

// wire.go:

var thirdSet = wire.NewSet(ioc.InitRedis, ioc.GetMysql, ioc.InitLogger, ioc.InitGoCache, ioc.InitSaramaKafka, event.NewAsyncLifeLogEventConsumer)

var lifelogSet = wire.NewSet(service.NewLifeLogService, repository.NewLifeLogRepository, dao.NewLifeLogDao, cache.NewLifeLogRedisCache, cache.NewLocalCache)
